// 10-question final test per topic. Option index 0 is always correct.

const q = (text, options) => ({
  text,
  options: options.map((o, i) => ({ text: o, isCorrect: i === 0 })),
});

module.exports = {
  A1: [
    q('Methodology is the scientific study of:',
      ['methods, approaches, and techniques', 'grammar rules only', 'literature', 'school administration']),
    q('Pedagogy refers to:',
      ['the general art of teaching', 'a specific method', 'a type of textbook', 'a grammar drill']),
    q('A technique is:',
      ['a specific classroom activity', 'the broadest theoretical view', 'a systematic plan', 'a long-term goal']),
    q('Didactics is best described as:',
      ['the theory of instruction', 'a type of test', 'a teaching aid', 'a CEFR level']),
    q('Modern methodology is mostly:',
      ['a living, evolving field', 'a fixed set of rules', 'a religious practice', 'a branch of literature']),
    q('Approach informs:',
      ['method, which shapes technique', 'tests, which shape lessons', 'grammar, which shapes vocabulary', 'curriculum, which shapes school']),
    q('Which discipline does methodology NOT typically draw from?',
      ['Carpentry', 'Linguistics', 'Psychology', 'Sociology']),
    q('A method differs from an approach in that it:',
      ['is more concrete and systematic', 'is older', 'is always wrong', 'avoids planning']),
    q('Understanding methodology helps teachers:',
      ['choose tools deliberately', 'memorise random rules', 'avoid teaching grammar', 'reject research']),
    q('"Approach > Method > Technique" is best described as:',
      ['a layered framework', 'a CEFR scale', 'a grammar tree', 'a vocabulary list']),
  ],

  A2: [
    q('Aims, content, and ___ are the three pillars of a lesson.',
      ['aids', 'tests', 'students', 'walls']),
    q('A practical aim usually targets:',
      ['communicative skills', 'religious values', 'physical exercise', 'national history']),
    q('A syllabus is:',
      ['a structured plan that sequences content', 'a type of audio drill', 'a CEFR descriptor', 'a piece of grammar']),
    q('Which is a teaching aid?',
      ['Flashcards', 'A learner\'s mood', 'A pronoun', 'A definite article']),
    q('The "four skills" of language are listening, speaking, ___, and writing.',
      ['reading', 'translating', 'shouting', 'whispering']),
    q('An upbringing aim helps form:',
      ['values and attitudes', 'spelling rules', 'phonemes', 'verb tenses']),
    q('Educational aim is mostly about:',
      ['broadening worldview', 'rote learning', 'physical fitness', 'spelling drills']),
    q('A well-designed lesson aligns:',
      ['aim, content, and aid', 'price, profit, and tax', 'fonts, colours, and images', 'desks, chairs, and walls']),
    q('Which is content rather than an aid?',
      ['Vocabulary', 'Flashcard', 'Whiteboard', 'Speaker']),
    q('A developing aim mainly fosters:',
      ['cognitive growth', 'memorisation only', 'physical strength', 'fashion sense']),
  ],

  A3: [
    q('Which method is most associated with translating literature?',
      ['Grammar-Translation', 'Direct Method', 'Audio-Lingual', 'TPR']),
    q('The Audio-Lingual Method relies on:',
      ['drills and repetition', 'free debate', 'silent reading', 'meditation']),
    q('The Communicative Approach prioritises:',
      ['real interaction tasks', 'memorising lists', 'translating poems', 'physical drills']),
    q('"Learning by doing" reflects the principle of:',
      ['activity', 'translation', 'silence', 'imitation']),
    q('Adapting teaching to each student is the principle of:',
      ['individualisation', 'standardisation', 'translation', 'punishment']),
    q('Which method banned the L1 from the classroom?',
      ['Direct Method', 'Grammar-Translation', 'CLIL', 'TBLT']),
    q('Modern teachers often work:',
      ['eclectically, mixing techniques', 'with one fixed method only', 'without any plan', 'in isolation from research']),
    q('A "conscious approach" means learners:',
      ['understand what they study', 'memorise without thinking', 'avoid grammar', 'speak only L1']),
    q('"Scientific basis" implies grounding in:',
      ['linguistics and psychology', 'mythology', 'astrology', 'cooking']),
    q('The Communicative Approach became dominant from the:',
      ['1980s', '1700s', '1920s', '1950s']),
  ],

  A4: [
    q('CEFR uses how many main levels?',
      ['Six', 'Three', 'Ten', 'Two']),
    q('IELTS scores range from:',
      ['1 to 9', '0 to 100', 'A to F', '1 to 5']),
    q('TOEFL iBT maximum score is:',
      ['120', '100', '900', '9']),
    q('A learner at A1 is considered:',
      ['beginner', 'advanced', 'native-like', 'expert']),
    q('Cambridge FCE corresponds to CEFR:',
      ['B2', 'A1', 'C2', 'A2']),
    q('Standardised tests are most useful for:',
      ['comparison across countries', 'replacing classroom teaching', 'avoiding curricula', 'firing teachers']),
    q('C2 is described as:',
      ['mastery', 'beginner', 'lower intermediate', 'pre-intermediate']),
    q('Tests should be used:',
      ['as one signal among many', 'as the only measure of ability', 'never', 'only by computers']),
    q('CEFR descriptors cover:',
      ['listening, reading, speaking, writing', 'only grammar', 'only vocabulary', 'only pronunciation']),
    q('Standardisation aims to make assessment:',
      ['fair and comparable', 'random', 'secret', 'expensive']),
  ],

  A5: [
    q('Grammar-Translation dominated in the:',
      ['19th century', '1980s', '1700s', '2020s']),
    q('The Reform Movement championed:',
      ['oral practice and spoken language', 'translation of poems', 'silence in class', 'phonetic dance']),
    q('Behaviourism is associated with:',
      ['stimulus and response', 'free will', 'mental grammar', 'critical thinking']),
    q('The cognitive revolution was led by:',
      ['Noam Chomsky', 'Henry Sweet', 'James Asher', 'Caleb Gattegno']),
    q('CLIL stands for:',
      ['Content and Language Integrated Learning', 'Centre for Language International Listening', 'Critical Listening Initial Level', 'Computer Linguistic Information Lab']),
    q('Eclecticism in teaching means:',
      ['borrowing techniques from many traditions', 'using only one method', 'inventing new languages', 'translating everything']),
    q('Task-based learning emphasises:',
      ['meaningful tasks first, language second', 'rote memorisation', 'silent reading only', 'physical drills only']),
    q('Audio-Lingual was influenced by:',
      ['behaviourism', 'cognitivism', 'humanism', 'constructivism']),
    q('Which is a recent trend?',
      ['Technology-enhanced instruction', 'Grammar-Translation revival', 'Silent reading only', 'Banning videos']),
    q('Modern teachers are often described as:',
      ['eclectic and research-informed', 'rigid and method-bound', 'opposed to research', 'indifferent to learners']),
  ],

  A6: [
    q('TPR stands for:',
      ['Total Physical Response', 'Translation Practice Routine', 'Teacher-Pupil Relationship', 'Topic-Personality Result']),
    q('TPR was developed by:',
      ['James Asher', 'Noam Chomsky', 'Stephen Krashen', 'Henry Sweet']),
    q('The Silent Way uses:',
      ['colored rods and pronunciation charts', 'long lectures', 'translation drills', 'role plays only']),
    q('Suggestopedia uses:',
      ['baroque music and comfortable seating', 'loud rock music', 'silent labs', 'physical drills']),
    q('CLL stands for:',
      ['Community Language Learning', 'Cognitive Linguistic Lab', 'Class Listening Lesson', 'Critical Language Logic']),
    q('CLL was inspired by:',
      ['Carl Rogers\'s psychotherapy', 'Behaviourism', 'Structural linguistics', 'Game theory']),
    q('Alternative approaches are often called:',
      ['humanistic', 'mechanical', 'random', 'punitive']),
    q('In Silent Way the teacher:',
      ['speaks as little as possible', 'speaks constantly', 'never enters class', 'sings songs']),
    q('Modern teaching has retained from these approaches:',
      ['concern for emotional safety', 'silent classrooms only', 'baroque music in every lesson', 'physical drills only']),
    q('Lozanov\'s aim with Suggestopedia was to:',
      ['tap into untapped learning potential', 'punish lazy students', 'replace teachers', 'ban grammar']),
  ],

  A7: [
    q('Roughly how many word families are needed for basic conversation?',
      ['2,000–3,000', '100', '50,000', '500,000']),
    q('Productive vocabulary is:',
      ['words a learner can actively use', 'words a learner only recognises', 'a textbook chapter', 'a CEFR level']),
    q('A collocation is:',
      ['words that typically go together', 'a grammar rule', 'a tense', 'a punctuation mark']),
    q('Recycling vocabulary means:',
      ['encountering words again in different contexts', 'throwing out old words', 'translating once', 'studying silently']),
    q('A lexical set is:',
      ['a group of words on a theme', 'a sentence pattern', 'a phonetic chart', 'a video lesson']),
    q('"Register" refers to:',
      ['formal or informal style', 'word frequency', 'punctuation', 'spelling']),
    q('Modern practice favours learning:',
      ['vocabulary in chunks', 'isolated words only', 'grammar before words', 'pronunciation only']),
    q('A connotation is:',
      ['the implied emotional meaning', 'a noun ending', 'a verb tense', 'a pronoun']),
    q('Knowing a word fully includes knowing its:',
      ['pronunciation, grammar, collocations, register', 'price', 'colour', 'origin country']),
    q('The PPP sequence stands for:',
      ['Present, Practice, Produce', 'Plan, Pause, Print', 'Pronounce, Pause, Pause', 'Pair, Push, Print']),
  ],

  A8: [
    q('Deductive grammar teaching presents:',
      ['the rule first, then examples', 'examples first, then the rule', 'no rules at all', 'only translation']),
    q('Inductive teaching encourages learners to:',
      ['discover rules from examples', 'memorise the rule verbatim', 'avoid examples', 'translate to L1']),
    q('PPP stands for:',
      ['Present, Practice, Produce', 'Plan, Punish, Praise', 'Pair, Push, Pull', 'Past, Present, Past']),
    q('Controlled practice mainly builds:',
      ['accuracy', 'creativity', 'fluency', 'pronunciation only']),
    q('Free production builds:',
      ['fluency', 'spelling only', 'silence', 'translation skills only']),
    q('The "noticing" hypothesis was proposed by:',
      ['Richard Schmidt', 'Stephen Krashen', 'Noam Chomsky', 'James Asher']),
    q('Task-based teaching addresses grammar:',
      ['after the task is completed', 'before any task', 'never', 'only in writing']),
    q('Inductive teaching is often:',
      ['more engaging but slower', 'always faster', 'identical to translation', 'unfocused']),
    q('Enhanced input means:',
      ['highlighting target structures visually', 'speaking very loudly', 'translating everything', 'ignoring grammar']),
    q('Which of these is form-focused?',
      ['Drilling verb endings', 'Free discussion', 'Watching a film silently', 'Reading for pleasure']),
  ],

  A9: [
    q('A minimal pair example is:',
      ['ship / sheep', 'cat / dog', 'happy / sad', 'go / went']),
    q('Modern pronunciation goal is:',
      ['intelligibility', 'sounding exactly like a native', 'silent reading', 'ignoring phonology']),
    q('Word stress is a:',
      ['suprasegmental feature', 'segmental feature', 'punctuation mark', 'grammar rule']),
    q('IPA stands for:',
      ['International Phonetic Alphabet', 'Initial Pronunciation Aid', 'Internal Phoneme Analysis', 'Inter-Personal Approach']),
    q('Weak forms appear in:',
      ['connected speech', 'isolated nouns', 'silent writing', 'translation']),
    q('A phoneme is:',
      ['a distinct unit of sound', 'a punctuation mark', 'a grammar form', 'a writing system']),
    q('Mirroring means:',
      ['imitating a model recording', 'looking in the mirror', 'translating sentences', 'silent reading']),
    q('Pronunciation is best:',
      ['integrated into other lessons', 'taught only in isolation', 'never taught', 'tested only']),
    q('The IPA helps learners:',
      ['see what they hear', 'memorise grammar', 'read literature', 'count syllables only']),
    q('Intonation changes affect:',
      ['meaning and attitude', 'spelling', 'word order', 'verb tense']),
  ],

  A10: [
    q('Adults typically spend more time:',
      ['listening', 'writing', 'reading', 'translating']),
    q('Bottom-up processing builds meaning from:',
      ['individual sounds and words', 'background knowledge', 'pictures only', 'cultural assumptions']),
    q('Top-down processing relies on:',
      ['prior knowledge and context', 'random guesses', 'silent reading', 'translating']),
    q('Pre-listening activities aim to:',
      ['activate background knowledge', 'replace listening', 'punish learners', 'transcribe audio']),
    q('Listening for gist means:',
      ['catching the main idea', 'remembering every word', 'transcribing the audio', 'translating into L1']),
    q('Authentic materials are:',
      ['real-world recordings', 'scripted only for learners', 'always slow', 'free of accents']),
    q('Listening for specific information targets:',
      ['names, dates, numbers', 'literary style', 'pronunciation only', 'word order']),
    q('Inference in listening means:',
      ['making logical deductions', 'translating word by word', 'silent waiting', 'random guesses']),
    q('Discourse markers signal:',
      ['turn-taking and topic shifts', 'phonemes', 'word stress', 'punctuation']),
    q('Skilled listeners use:',
      ['both bottom-up and top-down', 'only bottom-up', 'only top-down', 'no strategies']),
  ],

  A11: [
    q('Accuracy mainly concerns:',
      ['correct form', 'speed only', 'volume', 'gesture']),
    q('Fluency mainly concerns:',
      ['smooth, flowing speech', 'perfect grammar only', 'silent reading', 'translation skill']),
    q('A communicative task has:',
      ['a purpose and an information gap', 'no aim', 'a hidden meaning', 'no participants']),
    q('Correction in fluency activities is usually:',
      ['delayed', 'instant', 'absent entirely', 'in writing only']),
    q('Pragmatic competence includes:',
      ['knowing how to apologise appropriately', 'memorising tenses only', 'speaking loudly', 'reading aloud']),
    q('Pair work helps:',
      ['lower anxiety and increase practice', 'reduce learning', 'replace the teacher', 'cancel grammar']),
    q('A role play is a typical:',
      ['communicative activity', 'phonetic chart', 'literary genre', 'grammar drill']),
    q('Cultural appropriateness affects whether a learner:',
      ['sounds polite or rude', 'understands maths', 'can drive a car', 'plays an instrument']),
    q('Drills are at which end of the continuum?',
      ['Controlled', 'Free', 'Critical', 'Productive']),
    q('Thinking time before speaking:',
      ['improves output quality', 'wastes class time', 'is forbidden', 'is only for writing']),
  ],

  A12: [
    q('Skimming is reading to:',
      ['get the overall idea quickly', 'find a single number', 'translate in detail', 'study a single word']),
    q('Scanning is reading to:',
      ['locate specific information', 'enjoy literature', 'study grammar', 'check pronunciation']),
    q('Intensive reading focuses on:',
      ['short texts in detail', 'long easy texts', 'silent meditation', 'physical movement']),
    q('Extensive reading uses:',
      ['large quantities of easy material', 'short academic articles', 'silent writing only', 'grammar drills']),
    q('Inference in reading means:',
      ['making logical guesses about meaning', 'translating word by word', 'memorising the text', 'scanning numbers']),
    q('A pre-reading activity may:',
      ['activate schemata', 'replace the reading itself', 'test pronunciation only', 'cancel the lesson']),
    q('Extensive reading builds:',
      ['fluency and pleasure', 'silence only', 'a perfect accent', 'grammar drills']),
    q('A while-reading task often is:',
      ['answering comprehension questions', 'drawing a picture only', 'silent meditation', 'going home']),
    q('Post-reading typically:',
      ['exploits the text further', 'replaces reading', 'is forbidden', 'ignores meaning']),
    q('Reading exposes learners to:',
      ['authentic language', 'silent classrooms', 'mathematical formulas', 'physical exercise']),
  ],

  A13: [
    q('The Process Approach treats writing as:',
      ['a series of recursive stages', 'a single attempt', 'a memorised script', 'a phonetic drill']),
    q('The Genre Approach focuses on:',
      ['conventions of text types', 'random sentences', 'silent reading', 'oral debates']),
    q('Cohesion is achieved through:',
      ['linking words and reference', 'random punctuation', 'silent reading', 'oral drills']),
    q('Coherence concerns:',
      ['logical flow of ideas', 'spelling', 'pronunciation', 'word stress']),
    q('Drafting means producing:',
      ['a first version', 'the final copy', 'a translation', 'a phonetic chart']),
    q('Revising means:',
      ['changing content and organisation', 'fixing minor typos only', 'translating', 'reading aloud']),
    q('Editing means:',
      ['polishing language and mechanics', 'rewriting from scratch', 'guessing', 'silent reading']),
    q('Peer feedback helps learners:',
      ['develop a sense of audience', 'avoid all writing', 'replace the teacher', 'cancel revision']),
    q('Selective error correction targets:',
      ['a few important patterns', 'every minor mistake', 'no mistakes', 'spelling only']),
    q('Writing is challenging because it:',
      ['lacks immediate interaction', 'is too easy', 'requires no thought', 'has no audience']),
  ],

  A14: [
    q('Blended learning combines:',
      ['face-to-face and online activities', 'two foreign languages', 'two teachers', 'two textbooks']),
    q('The flipped classroom delivers:',
      ['content before the lesson', 'punishment first', 'tests at the start', 'lectures at home only']),
    q('Gamification adds:',
      ['points, badges, leaderboards', 'silent meditation', 'physical drills only', 'translation only']),
    q('CLIL stands for:',
      ['Content and Language Integrated Learning', 'Critical Listening Initial Level', 'Class Lesson In Lab', 'Cognitive Linguistic International Library']),
    q('AI chatbots in language learning offer:',
      ['conversation practice anytime', 'replacement of teachers', 'perfect grammar guarantees', 'silent classrooms']),
    q('Adaptive learning:',
      ['adjusts difficulty per learner', 'punishes mistakes', 'ignores progress', 'is only for adults']),
    q('A successful teacher:',
      ['selects useful innovations carefully', 'adopts every new tool blindly', 'rejects all technology', 'avoids research']),
    q('Duolingo is an example of:',
      ['gamified language learning', 'classical translation', 'silent reading', 'phonetic drill']),
    q('Innovation should address:',
      ['a real classroom need', 'the latest fashion', 'random ideas', 'teacher\'s ego']),
    q('AI writing feedback can:',
      ['identify errors and suggest improvements', 'replace human teachers entirely', 'guarantee perfect essays', 'translate at 100% accuracy']),
  ],

  A15: [
    q('Formative assessment is:',
      ['for ongoing learning improvement', 'only at the end of a course', 'always certified', 'never useful']),
    q('Summative assessment is:',
      ['at the end of learning', 'continuous and informal', 'a casual chat', 'a warm-up activity']),
    q('Validity means:',
      ['measuring what is claimed', 'being long', 'being expensive', 'being secret']),
    q('Reliability means:',
      ['consistent results across times', 'high cost', 'high difficulty', 'high speed']),
    q('Practicality concerns:',
      ['time, cost, feasibility', 'colour of the paper', 'student handwriting', 'teacher\'s mood']),
    q('Washback is the:',
      ['impact of assessment on teaching', 'noise of the test room', 'last test of the year', 'first test of the year']),
    q('A rubric makes scoring:',
      ['transparent and consistent', 'random', 'unfair', 'hidden']),
    q('A portfolio is:',
      ['a collection of learner work over time', 'a single test', 'a textbook', 'a teacher\'s diary']),
    q('Self-assessment helps learners:',
      ['reflect on their progress', 'cheat easily', 'avoid all learning', 'punish each other']),
    q('Good assessment systems combine:',
      ['multiple measures', 'a single test only', 'no measures', 'only standardized tests']),
  ],
};
